### ISSUE TITLE
Getting erros when trying to run it

### ISSUE THREAD

**Issue by aboubamba** [itm4n/PrivescCheck#51]
C:\temp>powershell -ep bypass -c "C:\temp\PrivescCheck.ps1; Invoke-PrivescCheck"
At C:\temp\PrivescCheck.ps1:40 char:60
+ ... script type="application/json" id="client-env">{"locale":"en","featur ...
+                                                             ~~~~~
Unexpected token ':"en"' in expression or statement.
At C:\temp\PrivescCheck.ps1:40 char:65
+ ... cript type="application/json" id="client-env">{"locale":"en","feature ...
+                                                                 ~
Missing argument in parameter list.
At C:\temp\PrivescCheck.ps1:40 char:285
+ ... _network_conn_type","no_character_key_shortcuts_in_inputs"]}</script>
+                                                                 ~
The '<' operator is reserved for future use.
At C:\temp\PrivescCheck.ps1:227 char:84
+ ... tion/json" data-target="react-partial.embeddedData">{"props":{}}</scr ...
+                                                                 ~
Unexpected token ':' in expression or statement.
At C:\temp\PrivescCheck.ps1:227 char:88
+ ... /json" data-target="react-partial.embeddedData">{"props":{}}</script>
+                                                                 ~
The '<' operator is reserved for future use.
At C:\temp\PrivescCheck.ps1:264 char:205
+ ... ink Button--medium Button d-lg-none color-fg-inherit p-1">  <span cla ...

**Comment by lap1nou** [comment]
Hello @aboubamba,

It's because you haven't downloaded PrivescCheck correctly, if you read your file you'll see some HTML because you have probably copy pasted or something like that which also copied the Github HTML source code. Either clone the repository or click the `Download raw file` button here: https://github.com/itm4n/PrivescCheck/blob/master/PrivescCheck.ps1 and then try to launch the script again.

Regards.

**Comment by aboubamba** [comment]
Ca marche maintenant, merci.
